# Aula 2.1 - Introdução aos arrays

### Arrays

    shape()

# Aula 2.2 - Criação de arrays

In [2]:
import numpy as np

In [9]:
# criação de um array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l, dtype = int)

print('x: ', x)
print('shape: ', x.shape)

x:  [1 2 3]
shape:  (3,)


In [5]:
# criação de um array 2D: listas aninhadas
l = [[1, 2], [3,4]]
x = np.array(l)

print('x: ', x)
print('shape: ', x.shape)

x:  [[1 2]
 [3 4]]
shape:  (2, 2)


In [6]:
# array contendo apenas 0's
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim)

print('x: ', x)
print('shape: ', x.shape)

x:  [[0. 0.]
 [0. 0.]]
shape:  (2, 2)


In [8]:
# array contendo apenas 1's
dim = (2, 2) # (linhas, colunas)
x = np.ones(dim)

print('x: ', x)
print('shape: ', x.shape)

x:  [[1. 1.]
 [1. 1.]]
shape:  (2, 2)


In [13]:
# criação de valores dentro de um intervalo
# valores linearmente espaçados entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start = x_min, stop = x_max, num = 6, dtype = int)

print('x: ', x)
print('shape: ', x.shape)

x:  [ 5  7  9 11 13 15]
shape:  (6,)


In [14]:
# criação de matriz identidade
n = 4
x = np.eye(n)

print('x: ', x)
print('shape: ', x.shape)

x:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [16]:
# criação de valores aleatórios
# np.random.seed(10)
x = np.random.random(size = (2, 3))

print('x: ', x)
print('shape: ', x.shape)

x:  [[0.29647171 0.77597367 0.10103057]
 [0.24241319 0.98901872 0.80130138]]
shape:  (2, 3)


# Aula 2.3 - Indexação de arrays

##### Acessando elementos:

- Acessando útilmo elemento de um array:
    A[-1]
- Acessando elementos em um array 2D: B[i,j] (indice da linha - axis 0 -, indice da coluna - axis 1)
- Slicing: A[1:3] - pegando index 1 até 2 (3 não incluído)
- Slicing 2D: B[1:3, 1:4] - pegando axis 0 de 1 a 2, e axis 1 de 1 a 3

### OBS:
**Ao editarmos o valor de uma entrada em um slice de um array, o valor será atualizado no array original!**

# Aula 2.4 - Indexação de arrays (prática)